# kube-prometheus-stack:
#   prometheus:
#     prometheusSpec:
#       retention: 15d
#       resources:
#         requests:
#           cpu: 500m
#           memory: 1Gi
#         limits:
#           cpu: 1
#           memory: 2Gi

  alertmanager:
    enabled: true
