replicaCount: 1

image:
  repository: docker.io/elumole22/movies-app
  tag: 0b4481d
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

prometheus:
  enabled: true
  scrapePath: /metrics
  scrapePort: "8000"

env:
  DATABASE_URL: ""

resources: {}

labels:
  app: movies-app
