kube-prometheus-stack:
  grafana:
    enabled: true
    service:
      type: ClusterIP
    image:
      repository: ghcr.io/grafana/grafana
      tag: 10.4.8
    grafana.ini:
      plugins:
        allow_loading_unsigned_plugins: yesoreyeram-infinity-datasource

  prometheus:
    prometheusSpec:
      retention: 3d
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector:
        any: true

  alertmanager:
    enabled: true


