{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
spec:
  provider:
    github:
      owner: {{ .Values.externalSecrets.github.owner }}
      repo: {{ .Values.externalSecrets.github.repo }}
      auth:
        tokenRef:
          name: github-token
          key: token
          namespace: external-secrets
{{- end }}
