{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secret.name }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: {{ .Values.externalSecrets.secret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.secret.name }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
{{- end }}
