{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
{{- end }}
