db_connection: "postgresql://dev-movies:movies@movies-db-dev-postgresql.dev.svc.cluster.local:5432/movies"

dbSeed:
  enabled: true

image:
  tag: "84677de"

rollout:
  enabled: false

hpa:
  enabled: true

externalSecrets:
  remoteKey: DEV_DATABASE_URL

ingress:
  enabled: true
  hosts:
    - host: movies-dev.local
      paths:
        - path: /
          pathType: Prefix
  service:
    name: movies-dev
    port: 80

