db_connection: "postgresql://prod-movies:movies@movies-db-prod-postgresql.prod.svc.cluster.local:5432/movies"

dbSeed:
  enabled: true

image:
  tag: "a717acc"

rollout:
  enabled: true

hpa:
  enabled: true