# db_connection: "postgresql://dev-movies:movies@movies-db-dev-postgresql.dev.svc.cluster.local:5432/movies"

dbSeed:
  enabled: true

image:
  tag: "9023df9"

rollout:
  enabled: false

hpa:
  enabled: true

externalSecrets:
  remoteKey: DEV_DATABASE_URL
