db_connection: "postgresql://staging-movies:movies@movies-db-staging-postgresql.staging.svc.cluster.local:5432/movies"

dbSeed:
  enabled: true

image:
  tag: "c01073e"

rollout:
  enabled: false

hpa:
  enabled: true

externalSecrets:
  remoteKey: STAGING_DATABASE_URL

ingress:
  enabled: true
  hosts:
    - host: movies-staging.local
      paths:
        - path: /
          pathType: Prefix
  service:
    name: movies-staging
    port: 80
